### ISSUE TITLE
PRQL code blocks are not rendered correctly with Quarto CLI 1.3 (preview)

### ISSUE THREAD

**Issue by eitsupi** [eitsupi/prqlr#109]
The `lang` option seems to be ignored.

I think a workaround is to use `engine` option instead of `lang` option here.

https://github.com/eitsupi/prqlr/blob/1ed9ca80bdcb20df4247959cd3baf584ba7f6011/R/knitr-engine.R#L22

**Comment by eitsupi** [comment]
I am wondering if I need to add a test to check the rendering results by Quarto.
As Quarto is not an R package and would require an additional step when running on GHA.

There is also the issue of whether the Quarto R package should be added as a dependency......

**Comment by cderv** [comment]
Yes you can do that (changing the `options$engine`) in your engine so that it is picked by Quarto 1.3. 

In next version, the `lang` option will be respected.

**Comment by eitsupi** [comment]
@cderv Thanks for your comment!
Does #110 look good?

**Comment by cderv** [comment]
> There is also the issue of whether the Quarto R package should be added as a dependency......

IMO you need only to add it (as Suggests) if you want to be thorough while adding a tests for Quarto in testthat while using `skip_on_cran()` and `skip_if_not_installed()`, and do snapshot test with markdown output. 

Otherwise you could have a specific workflow that do a check without being a tests in R for example and in that case no need to add as a dependency, and no need to run very frequently your test. 

By experience, hard to test everything that are output features. We'll check the knitr handling anyway.
