### ISSUE TITLE
Feature request: Allow for the use of ?variables on prql code chunks

### ISSUE THREAD

**Issue by andresrcs** [eitsupi/prqlr#92]
I would like to be able to use R variables inside prql code chunks as you can do with SQL code chunks, it would be useful for parameterized documents. For example:

````rmd
```{r}
#| echo: false

library(DBI)
library(prqlr)
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)

cyl_number <- 6
```

```{prql}
#| connection: con

from mtcars
filter cyl > ?cyl_number
select [cyl, mpg]
derive [mpg_int = round 0 mpg]
take 3
```
````
Or maybe is already possible but the syntax is different and is not documented?

**Comment by eitsupi** [comment]
Thank you for reporting this.

I believe these can be represented by the PRQL's s-strings feature.
https://prql-lang.org/book/language-features/s-strings.html

Like this:

````rmd
```{r}
#| echo: false

library(DBI)
library(prqlr)
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)

cyl_number <- 6
```

```{prql}
#| connection: con

from mtcars
filter cyl > s"?cyl_number"
select [cyl, mpg]
derive [mpg_int = round 0 mpg]
take 3
```
````

...But this fails.

It seems to be due to a space between `?` and `cyl_number` in the compiled SQL.

```r
> r"(from mtcars
    filter cyl > s"?cyl_number"
    select [cyl, mpg]
    derive [mpg_int = round 0 mpg]
    take 3)" |> prqlr::prql_compile() |> cat()
SELECT
  cyl,
  mpg,
  ROUND(mpg, 0) AS mpg_int
FROM
  mtcars
WHERE
  cyl > ? cyl_number
LIMIT
  3

-- Generated by PRQL compiler version:0.5.1 (https://prql-lang.org)
```

**Comment by eitsupi** [comment]
This is due to PRQL/prql#1284.

**Comment by eitsupi** [comment]
I tried to implement a way to use the `glue::glue()` function to replace strings before passing them to the prql-compiler, but I ran into a critical bug #100.
Once A is resolved, I think I can implement string replacement by glue.......

**Comment by eitsupi** [comment]
The PR is #103.
The syntax is as follows.

````rmd
```{r}
#| echo: false
library(prqlr)
cyl_min <- 6
derive_or_select <- "derive"
```
```{prql}
#| engine-opts:
#|   use_glue: true
from mtcars
filter cyl > {{cyl_min}}
select [cyl, mpg]
{{derive_or_select}} [mpg_int = round 0 mpg]
take 3
```
````

**Comment by andresrcs** [comment]
I really like the Jinja style syntax and since prql is significantly different than sql anyways I don't see a problem with adopting Jinja style syntax for parameterized code chunks
